version: '3.8'

services:
  api:
    container_name: aiotts_api
    build: .
    ports:
      - "1234:1234"
    networks:
      - aiotts_network
    restart: unless-stopped

networks:
  aiotts_network:
    driver: bridge