version: '3.8'

services:
  api:
    container_name: aiotts-backend-folinas
    build: .
    ports:
      - "1234:1234"
    networks:
      - aiotts_network
    restart: unless-stopped
    volumes:
      - ./update:/app/update
      - ./dependencies:/app/dependencies
      - ./uploads:/app/uploads

networks:
  aiotts_network:
    driver: bridge